on:
  push:
    branches:
      - master
  pull_request:
    branches: "*"

name: Project check
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16"
=======
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'
>>>>>>> 9be335d85cfdbcfa81eff5898d4275feea479831

      - uses: actions/checkout@master
        name: Checkout

      - name: Install dependencies
        run: |
          npm install

      - name: Run checks
        run: |
          npm test
